"""empty message

Revision ID: 1c76e300062a
Revises: 
Create Date: 2020-12-30 14:42:37.232736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c76e300062a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gauntlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('name_1', sa.String(length=50), nullable=True),
    sa.Column('name_2', sa.String(length=50), nullable=True),
    sa.Column('attribute_1', sa.Integer(), nullable=True),
    sa.Column('attribute_2', sa.Integer(), nullable=True),
    sa.Column('attribute_3', sa.Integer(), nullable=True),
    sa.Column('attribute_4', sa.Integer(), nullable=True),
    sa.Column('attribute_5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obstacle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('chance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_1', sa.String(length=50), nullable=True),
    sa.Column('name_2', sa.String(length=50), nullable=True),
    sa.Column('attribute_1', sa.Integer(), nullable=True),
    sa.Column('attribute_2', sa.Integer(), nullable=True),
    sa.Column('attribute_3', sa.Integer(), nullable=True),
    sa.Column('attribute_4', sa.Integer(), nullable=True),
    sa.Column('attribute_5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencer_event',
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer.id'], )
    )
    op.create_table('obstacle_event',
    sa.Column('obstacle_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['obstacle_id'], ['obstacle.id'], )
    )
    op.create_table('participant_event',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], )
    )
    op.create_table('trial_gauntlet',
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_gauntlet')
    op.drop_table('participant_event')
    op.drop_table('obstacle_event')
    op.drop_table('influencer_event')
    op.drop_table('trial')
    op.drop_table('participant')
    op.drop_table('obstacle')
    op.drop_table('influencer')
    op.drop_table('gauntlet')
    op.drop_table('event')
    # ### end Alembic commands ###
