"""empty message

Revision ID: 3641f5a02454
Revises: 1c76e300062a
Create Date: 2020-12-30 14:51:37.601801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3641f5a02454'
down_revision = '1c76e300062a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gauntlet_event',
    sa.Column('gauntlet_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['gauntlet_id'], ['gauntlet.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gauntlet_event')
    # ### end Alembic commands ###
