"""empty message

Revision ID: 526c31365bd7
Revises: a90aeef00a31
Create Date: 2021-01-02 12:44:11.037454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526c31365bd7'
down_revision = 'a90aeef00a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gauntlet_event',
    sa.Column('gauntlet_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['gauntlet_id'], ['gauntlet.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gauntlet_event')
    # ### end Alembic commands ###
