"""empty message

Revision ID: a90aeef00a31
Revises: d4f4c3db3770
Create Date: 2020-12-31 17:38:02.347881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90aeef00a31'
down_revision = 'd4f4c3db3770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_event',
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer.id'], )
    )
    op.create_table('participant_event',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_event')
    op.drop_table('influencer_event')
    # ### end Alembic commands ###
