"""empty message

Revision ID: aae33bf112f8
Revises: 1c73933f23ac
Create Date: 2020-12-31 16:45:26.447900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae33bf112f8'
down_revision = '1c73933f23ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gauntlet_event',
    sa.Column('gauntlet_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['gauntlet_id'], ['gauntlet.id'], )
    )
    op.create_table('influencer_event',
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer.id'], )
    )
    op.create_table('participant_event',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_event')
    op.drop_table('influencer_event')
    op.drop_table('gauntlet_event')
    # ### end Alembic commands ###
