"""empty message

Revision ID: c8fe5cf4966f
Revises: ab9caf7b042a
Create Date: 2020-12-31 15:00:46.552947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fe5cf4966f'
down_revision = 'ab9caf7b042a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gauntlet_event',
    sa.Column('gauntlet_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['gauntlet_id'], ['gauntlet.id'], )
    )
    op.create_table('influencer_event',
    sa.Column('influencer_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer.id'], )
    )
    op.create_table('participant_event',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], )
    )
    op.create_table('trial_gauntlet',
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_gauntlet')
    op.drop_table('participant_event')
    op.drop_table('influencer_event')
    op.drop_table('gauntlet_event')
    # ### end Alembic commands ###
